 version: 0.0
 os: linux
 files: 
   - source: /index.html
     destination: /var/www/html/
 hooks:
    BeforeInstall:
      - location: /install_dependencies
        timeout: 300
        runas: root
      - location: /start_server
        timeout: 300
        runas: root
    AfterInstall:
      - location: /home/ubuntu/edx/subodha/demo.sh
        timeout: 300
        runas: root 
     
